// Code generated by xgen. DO NOT EDIT.

package schema

import (
	"time"
)

// Document ...
type Document *Document

// AccountIdentification4Choice ...
type AccountIdentification4Choice struct {
	IBAN string                         `xml:"IBAN"`
	Othr *GenericAccountIdentification1 `xml:"Othr"`
}

// AccountOrBusinessError4Choice ...
type AccountOrBusinessError4Choice struct {
	Acct   *CashAccount37    `xml:"Acct"`
	BizErr []*ErrorHandling5 `xml:"BizErr"`
}

// AccountOrOperationalError4Choice ...
type AccountOrOperationalError4Choice struct {
	AcctRpt []*AccountReport24 `xml:"AcctRpt"`
	OprlErr []*ErrorHandling5  `xml:"OprlErr"`
}

// AccountReport24 ...
type AccountReport24 struct {
	AcctId    *AccountIdentification4Choice  `xml:"AcctId"`
	AcctOrErr *AccountOrBusinessError4Choice `xml:"AcctOrErr"`
}

// AccountSchemeName1Choice ...
type AccountSchemeName1Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// ActiveCurrencyAndAmountSimpleType ...
type ActiveCurrencyAndAmountSimpleType float64

// ActiveCurrencyAndAmount ...
type ActiveCurrencyAndAmount struct {
	CcyAttr string  `xml:"Ccy,attr"`
	Value   float64 `xml:",chardata"`
}

// ActiveCurrencyCode ...
type ActiveCurrencyCode string

// ActiveOrHistoricCurrencyCode ...
type ActiveOrHistoricCurrencyCode string

// AddressType2Code ...
type AddressType2Code string

// AddressType3Choice ...
type AddressType3Choice struct {
	Cd    string                   `xml:"Cd"`
	Prtry *GenericIdentification30 `xml:"Prtry"`
}

// Amount2Choice ...
type Amount2Choice struct {
	AmtWthtCcy float64                  `xml:"AmtWthtCcy"`
	AmtWthCcy  *ActiveCurrencyAndAmount `xml:"AmtWthCcy"`
}

// AnyBICDec2014Identifier ...
type AnyBICDec2014Identifier string

// BICFIDec2014Identifier ...
type BICFIDec2014Identifier string

// BalanceRestrictionType1 ...
type BalanceRestrictionType1 struct {
	Tp     *GenericIdentification1 `xml:"Tp"`
	Desc   string                  `xml:"Desc"`
	PrcgTp *ProcessingType1Choice  `xml:"PrcgTp"`
}

// BalanceStatus1Code ...
type BalanceStatus1Code string

// BalanceType11Choice ...
type BalanceType11Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// BalanceType9Choice ...
type BalanceType9Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// BilateralLimit3 ...
type BilateralLimit3 struct {
	CtrPtyId  *BranchAndFinancialInstitutionIdentification6 `xml:"CtrPtyId"`
	LmtAmt    *Amount2Choice                                `xml:"LmtAmt"`
	CdtDbtInd string                                        `xml:"CdtDbtInd"`
	BilBal    []*CashBalance11                              `xml:"BilBal"`
}

// BranchAndFinancialInstitutionIdentification6 ...
type BranchAndFinancialInstitutionIdentification6 struct {
	FinInstnId *FinancialInstitutionIdentification18 `xml:"FinInstnId"`
	BrnchId    *BranchData3                          `xml:"BrnchId"`
}

// BranchData3 ...
type BranchData3 struct {
	Id      string           `xml:"Id"`
	LEI     string           `xml:"LEI"`
	Nm      string           `xml:"Nm"`
	PstlAdr *PostalAddress24 `xml:"PstlAdr"`
}

// CashAccount37 ...
type CashAccount37 struct {
	Nm        string                                        `xml:"Nm"`
	Tp        *CashAccountType2Choice                       `xml:"Tp"`
	Ccy       string                                        `xml:"Ccy"`
	Prxy      *ProxyAccountIdentification1                  `xml:"Prxy"`
	CurMulLmt *Limit5                                       `xml:"CurMulLmt"`
	Ownr      *PartyIdentification135                       `xml:"Ownr"`
	Svcr      *BranchAndFinancialInstitutionIdentification6 `xml:"Svcr"`
	MulBal    []*CashBalance13                              `xml:"MulBal"`
	CurBilLmt []*BilateralLimit3                            `xml:"CurBilLmt"`
	StgOrdr   []*StandingOrder6                             `xml:"StgOrdr"`
}

// CashAccount38 ...
type CashAccount38 struct {
	Id   *AccountIdentification4Choice `xml:"Id"`
	Tp   *CashAccountType2Choice       `xml:"Tp"`
	Ccy  string                        `xml:"Ccy"`
	Nm   string                        `xml:"Nm"`
	Prxy *ProxyAccountIdentification1  `xml:"Prxy"`
}

// CashAccountType2Choice ...
type CashAccountType2Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// CashBalance11 ...
type CashBalance11 struct {
	Amt       float64                 `xml:"Amt"`
	CdtDbtInd string                  `xml:"CdtDbtInd"`
	Tp        *BalanceType9Choice     `xml:"Tp"`
	Sts       string                  `xml:"Sts"`
	ValDt     *DateAndDateTime2Choice `xml:"ValDt"`
	NbOfPmts  float64                 `xml:"NbOfPmts"`
}

// CashBalance13 ...
type CashBalance13 struct {
	Amt       float64                  `xml:"Amt"`
	CdtDbtInd string                   `xml:"CdtDbtInd"`
	Tp        *BalanceType11Choice     `xml:"Tp"`
	Sts       string                   `xml:"Sts"`
	ValDt     *DateAndDateTime2Choice  `xml:"ValDt"`
	PrcgDt    *DateAndDateTime2Choice  `xml:"PrcgDt"`
	NbOfPmts  float64                  `xml:"NbOfPmts"`
	RstrctnTp *BalanceRestrictionType1 `xml:"RstrctnTp"`
}

// ClearingSystemIdentification2Choice ...
type ClearingSystemIdentification2Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// ClearingSystemMemberIdentification2 ...
type ClearingSystemMemberIdentification2 struct {
	ClrSysId *ClearingSystemIdentification2Choice `xml:"ClrSysId"`
	MmbId    string                               `xml:"MmbId"`
}

// Contact4 ...
type Contact4 struct {
	NmPrfx    string           `xml:"NmPrfx"`
	Nm        string           `xml:"Nm"`
	PhneNb    string           `xml:"PhneNb"`
	MobNb     string           `xml:"MobNb"`
	FaxNb     string           `xml:"FaxNb"`
	EmailAdr  string           `xml:"EmailAdr"`
	EmailPurp string           `xml:"EmailPurp"`
	JobTitl   string           `xml:"JobTitl"`
	Rspnsblty string           `xml:"Rspnsblty"`
	Dept      string           `xml:"Dept"`
	Othr      []*OtherContact1 `xml:"Othr"`
	PrefrdMtd string           `xml:"PrefrdMtd"`
}

// CountryCode ...
type CountryCode string

// CreditDebitCode ...
type CreditDebitCode string

// DateAndDateTime2Choice ...
type DateAndDateTime2Choice struct {
	Dt   string `xml:"Dt"`
	DtTm string `xml:"DtTm"`
}

// DateAndPlaceOfBirth1 ...
type DateAndPlaceOfBirth1 struct {
	BirthDt     string `xml:"BirthDt"`
	PrvcOfBirth string `xml:"PrvcOfBirth"`
	CityOfBirth string `xml:"CityOfBirth"`
	CtryOfBirth string `xml:"CtryOfBirth"`
}

// DatePeriodDetails1 ...
type DatePeriodDetails1 struct {
	FrDt string `xml:"FrDt"`
	ToDt string `xml:"ToDt"`
}

// ErrorHandling3Choice ...
type ErrorHandling3Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// ErrorHandling5 ...
type ErrorHandling5 struct {
	Err  *ErrorHandling3Choice `xml:"Err"`
	Desc string                `xml:"Desc"`
}

// EventType1Choice ...
type EventType1Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// Exact4AlphaNumericText ...
type Exact4AlphaNumericText string

// ExecutionType1Choice ...
type ExecutionType1Choice struct {
	Tm  time.Time         `xml:"Tm"`
	Evt *EventType1Choice `xml:"Evt"`
}

// ExternalAccountIdentification1Code ...
type ExternalAccountIdentification1Code string

// ExternalCashAccountType1Code ...
type ExternalCashAccountType1Code string

// ExternalClearingSystemIdentification1Code ...
type ExternalClearingSystemIdentification1Code string

// ExternalEnquiryRequestType1Code ...
type ExternalEnquiryRequestType1Code string

// ExternalFinancialInstitutionIdentification1Code ...
type ExternalFinancialInstitutionIdentification1Code string

// ExternalOrganisationIdentification1Code ...
type ExternalOrganisationIdentification1Code string

// ExternalPaymentControlRequestType1Code ...
type ExternalPaymentControlRequestType1Code string

// ExternalPersonIdentification1Code ...
type ExternalPersonIdentification1Code string

// ExternalProxyAccountType1Code ...
type ExternalProxyAccountType1Code string

// ExternalSystemBalanceType1Code ...
type ExternalSystemBalanceType1Code string

// ExternalSystemErrorHandling1Code ...
type ExternalSystemErrorHandling1Code string

// ExternalSystemEventType1Code ...
type ExternalSystemEventType1Code string

// FinancialIdentificationSchemeName1Choice ...
type FinancialIdentificationSchemeName1Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// FinancialInstitutionIdentification18 ...
type FinancialInstitutionIdentification18 struct {
	BICFI       string                               `xml:"BICFI"`
	ClrSysMmbId *ClearingSystemMemberIdentification2 `xml:"ClrSysMmbId"`
	LEI         string                               `xml:"LEI"`
	Nm          string                               `xml:"Nm"`
	PstlAdr     *PostalAddress24                     `xml:"PstlAdr"`
	Othr        *GenericFinancialIdentification1     `xml:"Othr"`
}

// Frequency2Code ...
type Frequency2Code string

// GenericAccountIdentification1 ...
type GenericAccountIdentification1 struct {
	Id      string                    `xml:"Id"`
	SchmeNm *AccountSchemeName1Choice `xml:"SchmeNm"`
	Issr    string                    `xml:"Issr"`
}

// GenericFinancialIdentification1 ...
type GenericFinancialIdentification1 struct {
	Id      string                                    `xml:"Id"`
	SchmeNm *FinancialIdentificationSchemeName1Choice `xml:"SchmeNm"`
	Issr    string                                    `xml:"Issr"`
}

// GenericIdentification1 ...
type GenericIdentification1 struct {
	Id      string `xml:"Id"`
	SchmeNm string `xml:"SchmeNm"`
	Issr    string `xml:"Issr"`
}

// GenericIdentification30 ...
type GenericIdentification30 struct {
	Id      string `xml:"Id"`
	Issr    string `xml:"Issr"`
	SchmeNm string `xml:"SchmeNm"`
}

// GenericOrganisationIdentification1 ...
type GenericOrganisationIdentification1 struct {
	Id      string                                       `xml:"Id"`
	SchmeNm *OrganisationIdentificationSchemeName1Choice `xml:"SchmeNm"`
	Issr    string                                       `xml:"Issr"`
}

// GenericPersonIdentification1 ...
type GenericPersonIdentification1 struct {
	Id      string                                 `xml:"Id"`
	SchmeNm *PersonIdentificationSchemeName1Choice `xml:"SchmeNm"`
	Issr    string                                 `xml:"Issr"`
}

// IBAN2007Identifier ...
type IBAN2007Identifier string

// ISODate ...
type ISODate string

// ISODateTime ...
type ISODateTime string

// ISOTime ...
type ISOTime time.Time

// ImpliedCurrencyAndAmount ...
type ImpliedCurrencyAndAmount float64

// LEIIdentifier ...
type LEIIdentifier string

// Limit5 ...
type Limit5 struct {
	Amt       *Amount2Choice `xml:"Amt"`
	CdtDbtInd string         `xml:"CdtDbtInd"`
}

// Max128Text ...
type Max128Text string

// Max140Text ...
type Max140Text string

// Max16Text ...
type Max16Text string

// Max2048Text ...
type Max2048Text string

// Max34Text ...
type Max34Text string

// Max350Text ...
type Max350Text string

// Max35Text ...
type Max35Text string

// Max4Text ...
type Max4Text string

// Max70Text ...
type Max70Text string

// MessageHeader7 ...
type MessageHeader7 struct {
	MsgId       string                  `xml:"MsgId"`
	CreDtTm     string                  `xml:"CreDtTm"`
	ReqTp       *RequestType4Choice     `xml:"ReqTp"`
	OrgnlBizQry *OriginalBusinessQuery1 `xml:"OrgnlBizQry"`
	QryNm       string                  `xml:"QryNm"`
}

// NamePrefix2Code ...
type NamePrefix2Code string

// Number ...
type Number float64

// OrganisationIdentification29 ...
type OrganisationIdentification29 struct {
	AnyBIC string                                `xml:"AnyBIC"`
	LEI    string                                `xml:"LEI"`
	Othr   []*GenericOrganisationIdentification1 `xml:"Othr"`
}

// OrganisationIdentificationSchemeName1Choice ...
type OrganisationIdentificationSchemeName1Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// OriginalBusinessQuery1 ...
type OriginalBusinessQuery1 struct {
	MsgId   string `xml:"MsgId"`
	MsgNmId string `xml:"MsgNmId"`
	CreDtTm string `xml:"CreDtTm"`
}

// OtherContact1 ...
type OtherContact1 struct {
	ChanlTp string `xml:"ChanlTp"`
	Id      string `xml:"Id"`
}

// Party38Choice ...
type Party38Choice struct {
	OrgId  *OrganisationIdentification29 `xml:"OrgId"`
	PrvtId *PersonIdentification13       `xml:"PrvtId"`
}

// PartyIdentification135 ...
type PartyIdentification135 struct {
	Nm        string           `xml:"Nm"`
	PstlAdr   *PostalAddress24 `xml:"PstlAdr"`
	Id        *Party38Choice   `xml:"Id"`
	CtryOfRes string           `xml:"CtryOfRes"`
	CtctDtls  *Contact4        `xml:"CtctDtls"`
}

// PersonIdentification13 ...
type PersonIdentification13 struct {
	DtAndPlcOfBirth *DateAndPlaceOfBirth1           `xml:"DtAndPlcOfBirth"`
	Othr            []*GenericPersonIdentification1 `xml:"Othr"`
}

// PersonIdentificationSchemeName1Choice ...
type PersonIdentificationSchemeName1Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// PhoneNumber ...
type PhoneNumber string

// PostalAddress24 ...
type PostalAddress24 struct {
	AdrTp       *AddressType3Choice `xml:"AdrTp"`
	Dept        string              `xml:"Dept"`
	SubDept     string              `xml:"SubDept"`
	StrtNm      string              `xml:"StrtNm"`
	BldgNb      string              `xml:"BldgNb"`
	BldgNm      string              `xml:"BldgNm"`
	Flr         string              `xml:"Flr"`
	PstBx       string              `xml:"PstBx"`
	Room        string              `xml:"Room"`
	PstCd       string              `xml:"PstCd"`
	TwnNm       string              `xml:"TwnNm"`
	TwnLctnNm   string              `xml:"TwnLctnNm"`
	DstrctNm    string              `xml:"DstrctNm"`
	CtrySubDvsn string              `xml:"CtrySubDvsn"`
	Ctry        string              `xml:"Ctry"`
	AdrLine     []string            `xml:"AdrLine"`
}

// PreferredContactMethod1Code ...
type PreferredContactMethod1Code string

// ProcessingType1Choice ...
type ProcessingType1Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// ProcessingType1Code ...
type ProcessingType1Code string

// ProxyAccountIdentification1 ...
type ProxyAccountIdentification1 struct {
	Tp *ProxyAccountType1Choice `xml:"Tp"`
	Id string                   `xml:"Id"`
}

// ProxyAccountType1Choice ...
type ProxyAccountType1Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// RequestType4Choice ...
type RequestType4Choice struct {
	PmtCtrl string                  `xml:"PmtCtrl"`
	Enqry   string                  `xml:"Enqry"`
	Prtry   *GenericIdentification1 `xml:"Prtry"`
}

// ReturnAccountV08 ...
type ReturnAccountV08 struct {
	MsgHdr      *MessageHeader7                   `xml:"MsgHdr"`
	RptOrErr    *AccountOrOperationalError4Choice `xml:"RptOrErr"`
	SplmtryData []*SupplementaryData1             `xml:"SplmtryData"`
}

// StandingOrder6 ...
type StandingOrder6 struct {
	Amt             *Amount2Choice                                `xml:"Amt"`
	CdtDbtInd       string                                        `xml:"CdtDbtInd"`
	Ccy             string                                        `xml:"Ccy"`
	Tp              *StandingOrderType1Choice                     `xml:"Tp"`
	AssoctdPoolAcct *AccountIdentification4Choice                 `xml:"AssoctdPoolAcct"`
	Ref             string                                        `xml:"Ref"`
	Frqcy           string                                        `xml:"Frqcy"`
	VldtyPrd        *DatePeriodDetails1                           `xml:"VldtyPrd"`
	SysMmb          *BranchAndFinancialInstitutionIdentification6 `xml:"SysMmb"`
	RspnsblPty      *BranchAndFinancialInstitutionIdentification6 `xml:"RspnsblPty"`
	LkSetId         string                                        `xml:"LkSetId"`
	LkSetOrdrId     string                                        `xml:"LkSetOrdrId"`
	LkSetOrdrSeq    float64                                       `xml:"LkSetOrdrSeq"`
	ExctnTp         *ExecutionType1Choice                         `xml:"ExctnTp"`
	Cdtr            *BranchAndFinancialInstitutionIdentification6 `xml:"Cdtr"`
	CdtrAcct        *CashAccount38                                `xml:"CdtrAcct"`
	Dbtr            *BranchAndFinancialInstitutionIdentification6 `xml:"Dbtr"`
	DbtrAcct        *CashAccount38                                `xml:"DbtrAcct"`
	TtlsPerStgOrdr  *StandingOrderTotalAmount1                    `xml:"TtlsPerStgOrdr"`
	ZeroSweepInd    bool                                          `xml:"ZeroSweepInd"`
}

// StandingOrderTotalAmount1 ...
type StandingOrderTotalAmount1 struct {
	SetPrdfndOrdr *TotalAmountAndCurrency1 `xml:"SetPrdfndOrdr"`
	PdgPrdfndOrdr *TotalAmountAndCurrency1 `xml:"PdgPrdfndOrdr"`
	SetStgOrdr    *TotalAmountAndCurrency1 `xml:"SetStgOrdr"`
	PdgStgOrdr    *TotalAmountAndCurrency1 `xml:"PdgStgOrdr"`
}

// StandingOrderType1Choice ...
type StandingOrderType1Choice struct {
	Cd    string                  `xml:"Cd"`
	Prtry *GenericIdentification1 `xml:"Prtry"`
}

// StandingOrderType1Code ...
type StandingOrderType1Code string

// SupplementaryData1 ...
type SupplementaryData1 struct {
	PlcAndNm string                      `xml:"PlcAndNm"`
	Envlp    *SupplementaryDataEnvelope1 `xml:"Envlp"`
}

// SupplementaryDataEnvelope1 ...
type SupplementaryDataEnvelope1 struct {
}

// SystemBalanceType2Code ...
type SystemBalanceType2Code string

// TotalAmountAndCurrency1 ...
type TotalAmountAndCurrency1 struct {
	TtlAmt    float64 `xml:"TtlAmt"`
	CdtDbtInd string  `xml:"CdtDbtInd"`
	Ccy       string  `xml:"Ccy"`
}

// TrueFalseIndicator ...
type TrueFalseIndicator bool
