// Code generated by xgen. DO NOT EDIT.

package schema

// Document ...
type Document *Document

// AddressType2Code ...
type AddressType2Code string

// AddressType3Choice ...
type AddressType3Choice struct {
	Cd    string                   `xml:"Cd"`
	Prtry *GenericIdentification30 `xml:"Prtry"`
}

// BICFIDec2014Identifier ...
type BICFIDec2014Identifier string

// BranchAndFinancialInstitutionIdentification6 ...
type BranchAndFinancialInstitutionIdentification6 struct {
	FinInstnId *FinancialInstitutionIdentification18 `xml:"FinInstnId"`
	BrnchId    *BranchData3                          `xml:"BrnchId"`
}

// BranchData3 ...
type BranchData3 struct {
	Id      string           `xml:"Id"`
	LEI     string           `xml:"LEI"`
	Nm      string           `xml:"Nm"`
	PstlAdr *PostalAddress24 `xml:"PstlAdr"`
}

// ClearingSystemIdentification2Choice ...
type ClearingSystemIdentification2Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// ClearingSystemMemberIdentification2 ...
type ClearingSystemMemberIdentification2 struct {
	ClrSysId *ClearingSystemIdentification2Choice `xml:"ClrSysId"`
	MmbId    string                               `xml:"MmbId"`
}

// CountryCode ...
type CountryCode string

// DateTimePeriod1 ...
type DateTimePeriod1 struct {
	FrDtTm string `xml:"FrDtTm"`
	ToDtTm string `xml:"ToDtTm"`
}

// DateTimePeriod1Choice ...
type DateTimePeriod1Choice struct {
	FrDtTm string           `xml:"FrDtTm"`
	ToDtTm string           `xml:"ToDtTm"`
	DtTmRg *DateTimePeriod1 `xml:"DtTmRg"`
}

// EntryTypeIdentifier ...
type EntryTypeIdentifier string

// Exact4AlphaNumericText ...
type Exact4AlphaNumericText string

// ExternalClearingSystemIdentification1Code ...
type ExternalClearingSystemIdentification1Code string

// ExternalFinancialInstitutionIdentification1Code ...
type ExternalFinancialInstitutionIdentification1Code string

// FinancialIdentificationSchemeName1Choice ...
type FinancialIdentificationSchemeName1Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// FinancialInstitutionIdentification18 ...
type FinancialInstitutionIdentification18 struct {
	BICFI       string                               `xml:"BICFI"`
	ClrSysMmbId *ClearingSystemMemberIdentification2 `xml:"ClrSysMmbId"`
	LEI         string                               `xml:"LEI"`
	Nm          string                               `xml:"Nm"`
	PstlAdr     *PostalAddress24                     `xml:"PstlAdr"`
	Othr        *GenericFinancialIdentification1     `xml:"Othr"`
}

// GenericFinancialIdentification1 ...
type GenericFinancialIdentification1 struct {
	Id      string                                    `xml:"Id"`
	SchmeNm *FinancialIdentificationSchemeName1Choice `xml:"SchmeNm"`
	Issr    string                                    `xml:"Issr"`
}

// GenericIdentification30 ...
type GenericIdentification30 struct {
	Id      string `xml:"Id"`
	Issr    string `xml:"Issr"`
	SchmeNm string `xml:"SchmeNm"`
}

// ISODate ...
type ISODate string

// ISODateTime ...
type ISODateTime string

// ImpliedCurrencyAndAmount ...
type ImpliedCurrencyAndAmount float64

// Instruction1Code ...
type Instruction1Code string

// LEIIdentifier ...
type LEIIdentifier string

// LongPaymentIdentification2 ...
type LongPaymentIdentification2 struct {
	TxId           string                                        `xml:"TxId"`
	UETR           string                                        `xml:"UETR"`
	IntrBkSttlmAmt float64                                       `xml:"IntrBkSttlmAmt"`
	IntrBkSttlmDt  string                                        `xml:"IntrBkSttlmDt"`
	PmtMtd         *PaymentOrigin1Choice                         `xml:"PmtMtd"`
	InstgAgt       *BranchAndFinancialInstitutionIdentification6 `xml:"InstgAgt"`
	InstdAgt       *BranchAndFinancialInstitutionIdentification6 `xml:"InstdAgt"`
	NtryTp         string                                        `xml:"NtryTp"`
	EndToEndId     string                                        `xml:"EndToEndId"`
}

// Max140Text ...
type Max140Text string

// Max16Text ...
type Max16Text string

// Max350Text ...
type Max350Text string

// Max35Text ...
type Max35Text string

// Max3NumericText ...
type Max3NumericText string

// Max70Text ...
type Max70Text string

// MessageHeader1 ...
type MessageHeader1 struct {
	MsgId   string `xml:"MsgId"`
	CreDtTm string `xml:"CreDtTm"`
}

// ModifyTransactionV08 ...
type ModifyTransactionV08 struct {
	MsgHdr      *MessageHeader1             `xml:"MsgHdr"`
	Mod         []*TransactionModification5 `xml:"Mod"`
	SplmtryData []*SupplementaryData1       `xml:"SplmtryData"`
}

// PaymentIdentification6Choice ...
type PaymentIdentification6Choice struct {
	TxId      string                           `xml:"TxId"`
	QId       *QueueTransactionIdentification1 `xml:"QId"`
	LngBizId  *LongPaymentIdentification2      `xml:"LngBizId"`
	ShrtBizId *ShortPaymentIdentification2     `xml:"ShrtBizId"`
	PrtryId   string                           `xml:"PrtryId"`
}

// PaymentInstruction33 ...
type PaymentInstruction33 struct {
	Instr       string                 `xml:"Instr"`
	Tp          *PaymentType4Choice    `xml:"Tp"`
	Prty        *Priority1Choice       `xml:"Prty"`
	PrcgVldtyTm *DateTimePeriod1Choice `xml:"PrcgVldtyTm"`
}

// PaymentInstrument1Code ...
type PaymentInstrument1Code string

// PaymentOrigin1Choice ...
type PaymentOrigin1Choice struct {
	FINMT    string `xml:"FINMT"`
	XMLMsgNm string `xml:"XMLMsgNm"`
	Prtry    string `xml:"Prtry"`
	Instrm   string `xml:"Instrm"`
}

// PaymentType3Code ...
type PaymentType3Code string

// PaymentType4Choice ...
type PaymentType4Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// PostalAddress24 ...
type PostalAddress24 struct {
	AdrTp       *AddressType3Choice `xml:"AdrTp"`
	Dept        string              `xml:"Dept"`
	SubDept     string              `xml:"SubDept"`
	StrtNm      string              `xml:"StrtNm"`
	BldgNb      string              `xml:"BldgNb"`
	BldgNm      string              `xml:"BldgNm"`
	Flr         string              `xml:"Flr"`
	PstBx       string              `xml:"PstBx"`
	Room        string              `xml:"Room"`
	PstCd       string              `xml:"PstCd"`
	TwnNm       string              `xml:"TwnNm"`
	TwnLctnNm   string              `xml:"TwnLctnNm"`
	DstrctNm    string              `xml:"DstrctNm"`
	CtrySubDvsn string              `xml:"CtrySubDvsn"`
	Ctry        string              `xml:"Ctry"`
	AdrLine     []string            `xml:"AdrLine"`
}

// Priority1Choice ...
type Priority1Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// Priority5Code ...
type Priority5Code string

// QueueTransactionIdentification1 ...
type QueueTransactionIdentification1 struct {
	QId    string `xml:"QId"`
	PosInQ string `xml:"PosInQ"`
}

// ShortPaymentIdentification2 ...
type ShortPaymentIdentification2 struct {
	TxId          string                                        `xml:"TxId"`
	IntrBkSttlmDt string                                        `xml:"IntrBkSttlmDt"`
	InstgAgt      *BranchAndFinancialInstitutionIdentification6 `xml:"InstgAgt"`
}

// SupplementaryData1 ...
type SupplementaryData1 struct {
	PlcAndNm string                      `xml:"PlcAndNm"`
	Envlp    *SupplementaryDataEnvelope1 `xml:"Envlp"`
}

// SupplementaryDataEnvelope1 ...
type SupplementaryDataEnvelope1 struct {
}

// TransactionModification5 ...
type TransactionModification5 struct {
	PmtId        *PaymentIdentification6Choice `xml:"PmtId"`
	NewPmtValSet *PaymentInstruction33         `xml:"NewPmtValSet"`
}

// UUIDv4Identifier ...
type UUIDv4Identifier string
